ProjektGrupowy/Panel/Models/EventConfigurationViewModel.cs
using Data.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Panel.Models
{
    public class EventConfigurationViewModel
    {
        public List<EventConfigRow> Configurations { get; set; }

        public List<UserDataProperty> Properties { get; set; }

        public CurrentConfig CurrentConfig { get; set; }

        public string Response { get; set; }
    }

    public class EventConfigRow
    {
        public int Id { get; set; }
        
        public string Rule { get; set; }

        public int Period { get; set; }
    }

    public class CurrentConfig
    {
        public string Id { get; set; }

        [Required]
        [Range(-100, int.MaxValue)]
        public int PropertyId { get; set; }

        public IEnumerable<SelectListItem> PropertyList { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string PropertyOperator { get; set; }
        
        public IEnumerable<SelectListItem> PropertyOperatorList { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string PropertyValue { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Operator { get; set; }

        public IEnumerable<SelectListItem> OperatorList { get; set; }

        [Required]
        [Range(0, int.MaxValue)]
        public string ResultValue { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Function { get; set; }

        public IEnumerable<SelectListItem> FunctionList { get; set; }

        [Required]
        [Range(1, int.MaxValue)]
        public string Period { get; set; }

        [Required]
        [AllowHtml]
        [DataType(DataType.Html)]
        public string Template { get; set; }
        
        [DataType(DataType.Text)]
        public string TemplateProperties { get; set; }
    }
}

ProjektGrupowy/Panel/Controllers/EventConfigurationController.cs
using Common.Helpers;
using Common.Logging;
using Database.Models;
using Panel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Panel.Controllers
{
    [Authorize]
    public class EventConfigurationController : Controller
    {
        private readonly Logger _logger = new Logger("EventConfigurationController");

        public ActionResult Index()
        {
            var model = GetModel();

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Add(EventConfigurationViewModel data)
        {
            var response = string.Empty;
            try
            {
                if (ModelState.IsValid)
                {
                    int userId = UserHelper.GetUserByIdentityName(User.Identity.Name).Id;
                    var config = GetEventConfigurationFromForm(userId, data.CurrentConfig);

                    if (IsNewConfiguration(data.CurrentConfig.Id))
                    {
                        EventConfigurationHelper.AddConfiguration(config);
                        response = "Event Configuration added successfully";
                    }
                    else
                    {
                        EventConfigurationHelper.UpdateConfiguration(config);
                        response = "Event Configuration updated successfully";
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);
            }

            var model = GetModel();
            model.Response = response;

            return View("Index", model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var model = GetModel();

            try
            {
                int userId = UserHelper.GetUserByIdentityName(User.Identity.Name).Id;

                var  config = EventConfigurationHelper.GetConfiguration(id);
                model.CurrentConfig = GetCurrentConfig(config, userId);
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);
            }

            return View("Index", model);
        }

        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var config = EventConfigurationHelper.GetConfiguration(id);
                EventConfigurationHelper.DeleteConfiguration(config);
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);
            }

            var model = GetModel();
            model.Response = "Event Configuration deleted successfully";

            return View("Index", model);
        }

        private EventConfigurationViewModel GetModel()
        {
            int userId = UserHelper.GetUserByIdentityName(User.Identity.Name).Id;

            var configs = EventConfigurationHelper.GetUserEventConfigurations(userId);

            var model = new EventConfigurationViewModel()
            {
                Configurations = new List<EventConfigRow>(),
                Properties = DataConfigurationHelper.GetUserDataProperties(userId),
                CurrentConfig = GetEmptyCurrentConfig(userId),
                Response = string.Empty
            };

            foreach (var config in configs)
            {
                model.Configurations.Add(new EventConfigRow
                {
                    Id = config.Id,
                    Rule = EventConfigurationHelper.FormatEventToString(config),
                    Period = config.Period
                });
            }

            return model;
        }

        private bool IsNewConfiguration(string id)
        {
            return string.IsNullOrEmpty(id);
        }

        private EventConfiguration GetEventConfigurationFromForm(int userId, CurrentConfig config)
        {
            var eventConfig = new EventConfiguration
            {
                PropertyId = config.PropertyId,
                PropertyOperator = config.PropertyOperator,
                PropertyValue = config.PropertyValue,
                Operator = config.Operator,
                ResultValue = Convert.ToInt32(config.ResultValue),
                Function = config.Function,
                Period = Convert.ToInt32(config.Period),
                UserId = userId,
                Template = config.Template,
                TemplateProperties = EventConfigurationHelper.ConvertTemplatePropertiesFromNamesToIds(config.TemplateProperties),
                Category = string.Empty,
                CategoryId = 0
            };

            if (!IsNewConfiguration(config.Id))
            {
                eventConfig.Id = Convert.ToInt32(config.Id);
            }

            return eventConfig;
        }

        private CurrentConfig GetCurrentConfig(EventConfiguration config, int userId)
        {
            var operators = new List<string>() { "=", "<", ">" };
            var functions = new List<string>() { "SUM", "AVG", "COUNT" };
            var properties = DataConfigurationHelper.GetUserDataProperties(userId);

            return new CurrentConfig
            {
                Id = config.Id.ToString(),
                PropertyId = config.PropertyId,
                PropertyList =
                    properties.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString(),
                        Selected = x.Id == config.PropertyId
                    }),
                PropertyOperator = config.PropertyOperator,
                PropertyOperatorList =
                    operators.Select(x => new SelectListItem
                    {
                        Text = x,
                        Value = x,
                        Selected = x == config.PropertyOperator
                    }),
                PropertyValue = config.PropertyValue,
                Operator = config.Operator,
                OperatorList =
                    operators.Select(x => new SelectListItem
                    {
                        Text = x,
                        Value = x,
                        Selected = x == config.Operator
                    }),
                ResultValue = config.ResultValue.ToString(),
                Function = config.Function,
                FunctionList =
                    functions.Select(x => new SelectListItem
                    {
                        Text = x,
                        Value = x,
                        Selected = x == config.Function
                    }),
                Period = config.Period.ToString(),
                Template = config.Template,
                TemplateProperties = EventConfigurationHelper.ConvertTemplatePropertiesFromIdsToNames(config.TemplateProperties)
            };
        }

        private CurrentConfig GetEmptyCurrentConfig(int userId)
        {
            var operators = new List<string>() { "=", "<", ">" };
            var functions = new List<string>() { "SUM", "AVG", "COUNT" };
            var properties = DataConfigurationHelper.GetUserDataProperties(userId);

            return new CurrentConfig
            {
                Id = string.Empty,
                PropertyList =
                    properties.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString(),
                        Selected = x.Id == properties.First().Id
                    }),
                PropertyOperatorList =
                    operators.Select(x => new SelectListItem
                    {
                        Text = x,
                        Value = x,
                        Selected = x == operators.First()
                    }),
                PropertyValue = string.Empty,
                OperatorList =
                    operators.Select(x => new SelectListItem
                    {
                        Text = x,
                        Value = x,
                        Selected = x == operators.First()
                    }),
                ResultValue = string.Empty,
                FunctionList =
                    functions.Select(x => new SelectListItem
                    {
                        Text = x,
                        Value = x,
                        Selected = x == functions.First()
                    }),
                Period = string.Empty,
                Template = string.Empty,
                TemplateProperties = string.Empty
            };
        }
    }
}

ProjektGrupowy/Panel/Views/EventConfiguration/Index.cshtml
@model Panel.Models.EventConfigurationViewModel
@{
    ViewBag.Title = "Event Configuration";
}

<div class="container">
<div class="row">
    <h2>Event Configuration</h2>
</div>
<div class="row">
    <table id="" class="table table-hover">
        <thead>
            <tr>
                <th>Event rule</th>
                <th>Period</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{ 
                foreach (var item in Model.Configurations)
                {
                    <tr>
                        <td>
                            @Html.Raw(item.Rule)
                        </td>
                        <td>
                            @Html.Encode(item.Period)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<div class="row">
    <p>Function(property [property_operator] property_value) [operator] value</p>
</div>
<div class="row">
    @using (Html.BeginForm("Add", "EventConfiguration", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <div class="row">
            @Html.Raw(Model.Response)
            @Html.ValidationSummary("", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            <label for="function-input">Function:</label>
            @Html.DropDownListFor(x => x.CurrentConfig.Function, Model.CurrentConfig.FunctionList, new { @id = "function-input", @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="property-input">Property:</label>
            @Html.DropDownListFor(x => x.CurrentConfig.PropertyId, Model.CurrentConfig.PropertyList, new { @id = "property-input", @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="property-operator-input">Property operator:</label>
            @Html.DropDownListFor(x => x.CurrentConfig.PropertyOperator, Model.CurrentConfig.PropertyOperatorList, new { @id = "property-operator-input", @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="property-value-input">Property value:</label>
            @Html.TextBoxFor(x => x.CurrentConfig.PropertyValue, new { @id = "property-value-input", @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="operator-input">Operator:</label>
            @Html.DropDownListFor(x => x.CurrentConfig.Operator, Model.CurrentConfig.OperatorList, new { @id = "operator-input", @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="value-input">Value:</label>
            @Html.TextBoxFor(x => x.CurrentConfig.ResultValue, new { @id = "value-input", @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="period-input">Period (number of days):</label>
            @Html.TextBoxFor(x => x.CurrentConfig.Period, new { @id = "period-input", @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="template-input">Template (html Code):</label>
            @Html.TextAreaFor(x => x.CurrentConfig.Template, new { @id = "template-input", @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="template-properties-input">Template Properties (names splitted by ,):</label>
            @Html.TextBoxFor(x => x.CurrentConfig.TemplateProperties, new { @id = "template-properties-input", @class = "form-control" })
        </div>
        @Html.HiddenFor(x => x.CurrentConfig.Id);
        <button type="submit" class="btn btn-default">Submit</button>
    }
</div>
</div>